name: ✨ Feature Request
description: Propose a new NetBox feature or enhancement
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This form is only for submitting well-formed proposals to extend or modify
        > NetBox **Helm charts** in some way.
        > If you're trying to solve a problem but can't figure out how, or if
        > you still need time to work on the details of a proposed new feature, please start a
        > [discussion](https://github.com/netbox-community/netbox/discussions) instead.
  - type: textarea
    attributes:
      label: Proposed functionality
      description: |
        Describe in detail the new feature or behavior you are proposing. Include any specific changes
        to work flows, data models, and/or the user interface. The more detail you provide here, the
        greater chance your proposal has of being discussed. Feature requests which don't include an
        actionable implementation plan will be rejected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        Explain how adding this functionality would benefit NetBox users when using its Helm chart.
        What need does it address?
    validations:
      required: true
