{{- if .Values.housekeeping.enabled -}}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "netbox.fullname" . }}-housekeeping
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: housekeeping
spec:
  concurrencyPolicy: {{ .Values.housekeeping.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.housekeeping.failedJobsHistoryLimit }}
  schedule: {{ .Values.housekeeping.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.housekeeping.successfulJobsHistoryLimit }}
  suspend: {{ .Values.housekeeping.suspend }}
  jobTemplate:
    metadata:
      labels:
        {{- include "netbox.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          {{- with .Values.housekeeping.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "netbox.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: housekeeping
            {{- with .Values.housekeeping.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "netbox.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.housekeeping.podSecurityContext | nindent 12 }}
          {{- with .Values.housekeeping.extraInitContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}-housekeeping
              securityContext:
                {{- toYaml .Values.housekeeping.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command:
                - /opt/netbox/venv/bin/python
                - /opt/netbox/netbox/manage.py
                - housekeeping
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.housekeeping.extraEnvs }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: config
                  mountPath: /etc/netbox/config/configuration.py
                  subPath: configuration.py
                  readOnly: true
                {{ if eq .Values.remoteAuth.backend "netbox.authentication.LDAPBackend" -}}
                - name: config
                  mountPath: /etc/netbox/config/ldap/ldap_config.py
                  subPath: ldap_config.py
                  readOnly: true
                {{ end -}}
                - name: config
                  mountPath: /run/config/netbox
                  readOnly: true
                - name: secrets
                  mountPath: /run/secrets/netbox
                  readOnly: true
                {{- include "netbox.extraConfig.volumeMounts" . | nindent 16 -}}
                - name: netbox-tmp
                  mountPath: /tmp
                - name: media
                  mountPath: /opt/netbox/netbox/media
                  subPath: {{ .Values.persistence.subPath | default "" | quote }}
                {{- if .Values.reportsPersistence.enabled }}
                - name: reports
                  mountPath: /opt/netbox/netbox/reports
                  subPath: {{ .Values.reportsPersistence.subPath | default "" | quote }}
                {{- end }}
                {{- with .Values.housekeeping.extraVolumeMounts }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- if .Values.housekeeping.resources }}
              resources:
                {{- toYaml .Values.housekeeping.resources | nindent 16 }}
              {{- end }}
            {{- with .Values.housekeeping.extraContainers }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumes:
            - name: config
              configMap:
                name: {{ include "netbox.fullname" . }}
            - name: secrets
              projected:
                sources:
                  - secret:
                      name: {{ .Values.existingSecret | default (include "netbox.fullname" .) | quote }}
                      items:
                        # Used by our configuration
                        - key: email_password
                          path: email_password
                        - key: napalm_password
                          path: napalm_password
                        - key: secret_key
                          path: secret_key
                        {{- if eq .Values.remoteAuth.backend "netbox.authentication.LDAPBackend" }}
                        - key: ldap_bind_password
                          path: ldap_bind_password
                        {{- end }}
                  - secret:
                      name: {{ include "netbox.postgresql.secret" . | quote }}
                      items:
                        - key: {{ include "netbox.postgresql.secretKey" . | quote }}
                          path: db_password
                  - secret:
                      name: {{ include "netbox.tasksRedis.secret" . | quote }}
                      items:
                        - key: {{ include "netbox.tasksRedis.secretKey" . | quote }}
                          path: redis_tasks_password
                  - secret:
                      name: {{ include "netbox.cachingRedis.secret" . | quote }}
                      items:
                        - key: {{ include "netbox.cachingRedis.secretKey" . | quote }}
                          path: redis_cache_password
            {{- include "netbox.extraConfig.volumes" . | nindent 12 -}}
            - name: netbox-tmp
              emptyDir:
                medium: Memory
            - name: media
              {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.existingClaim | default (printf "%s-media" (include "netbox.fullname" .)) }}
              {{- else }}
              emptyDir: {}
              {{- end }}
            {{- if .Values.reportsPersistence.enabled }}
            - name: reports
              persistentVolumeClaim:
                claimName: {{ .Values.reportsPersistence.existingClaim | default (printf "%s-reports" (include "netbox.fullname" .)) }}
            {{- end }}
            {{- with .Values.housekeeping.extraVolumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.housekeeping.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.housekeeping.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.housekeeping.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.housekeeping.restartPolicy }}
{{- end -}}
